{% set name = "dqsegdb2" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 378da7e5c28bdee5581c4dce367238e93d1303ba86540e74a3daa6473f872a40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - igwn-auth-utils
    - ligo-segments
    - python >=3.6
    # extras for igwn-auth-utils[requests]
    - requests
    - safe-netrc

test:
  requires:
    - pip
    - pytest
    - requests-mock
  commands:
    # check metadata
    - python -m pip check
    # run test suite
    - python -m pytest --pyargs dqsegdb2 -ra -v

about:
  home: https://dqsegdb2.readthedocs.io
  doc_url: https://dqsegdb2.readthedocs.io
  dev_url: https://github.com/duncanmmacleod/dqsegdb2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A simplified Python implementation of the DQSegDB API
  description: |
    This package only provides a query interface for `GET` requests for a
    subset of information available from a DQSegDB server.
    Any users wishing to make `POST` requests should refer to the official
    DQSegDB Python client available from https://pypi.org/project/dqsegdb.

extra:
  recipe-maintainers:
    - duncanmmacleod
