{% set name = "dqsegdb2" %}
{% set version = "1.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a222dbb7024de6de845ba5ad3583859cecf8ed5ce584ff5db6f01581b821f81

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4.3
  run:
    - igwn-auth-utils >=1.0.0
    - ligo-segments >=1.0.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest >=2.9.2
    - requests-mock >=1.5.0
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show dqsegdb2
    # run test suite
    - python -m pytest --pyargs dqsegdb2 -ra -v

about:
  home: https://dqsegdb2.readthedocs.io
  doc_url: https://dqsegdb2.readthedocs.io
  dev_url: https://git.ligo.org/duncanmmacleod/dqsegdb2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A simplified Python implementation of the DQSegDB API
  description: |
    This package only provides a query interface for `GET` requests for a
    subset of information available from a DQSegDB server.
    Any users wishing to make `POST` requests should refer to the official
    DQSegDB Python client available from https://pypi.org/project/dqsegdb.

extra:
  recipe-maintainers:
    - duncanmmacleod
