appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: opMc10e0/kbhEOIt2uO2vY3ICILgaD+Tv3Myf3csz6k1VQo26yG2jTTTaXQyPyw8rWPKJmUJaFGdC2xl8lyfRdqQ/2vAELQC/ravxYdOKwqXuJlW05BC7y6UjFI9aFlNidjkWv1THn6eHN/fCsYFxuCh5i3tfCY3GlCFFJrd/8A9jd82RZWSzr6RtrX8Qa6g5twZP6k/od2KZtuo6+C/I7UpmrA48cN0k50gdy13H7nfiMoAfz4XoBNM0wZcaAv2CkObSmj3I8JkRagX9WP9wG9FX6V2JD+pudOx4aQGmLR2kDz5mDH9Jki+dFITpjrNj4wJrCOrg2CN5xtDWdu5c2LrJ58+XAjtYwXq2/fg1cyEPU61UuL73bQavSaXvpY6Vc2CaUDWezo8hFTDz6GItHSk0bSv04VY/eHw67rm6SrrVdA5Kx3bjXR5f4HRn4o8nQ6QCrp7sAnDLQUpa4dMCQmYUCWBBASg+yKmH3dUMxdiCUqacLRP+pq3Jo+87InKeSne+hAmSmmgafZmqnepWiYGwRmdvihmMFEzxEsnkQK8RnBXLAVHOYXiCkIHF+xYUqiGByonrPkcHq421gMhHdI4qvhE/B8SskMkTDvnPaCwx1UjPc+ob9K9iySwQN1Demfmlv2+hiqSVnCTINzSPyFp2vdU3Lz1i7Ynl2g20Es=}
conda_forge_output_validation: true
